#!/bin/sh
n=$1
shift
[ -z "$n" ] && echo usage: "$0 NUM" && exit 55
if [ $n -lt 1 -o $n -gt 39 ] ; then
  echo "$n out of range"
  exit 56
fi

# workaround libvirtd disappearance:
pidof libvirtd || /usr/local/sbin/fixlibvirt
cloudfunc=~/cloud.d/cloudfunc
test -e $cloudfunc || cloudfunc=$(dirname $(readlink -e $BASH_SOURCE))/cloudfunc
. $cloudfunc

#export cloudsource=GM2.0
#export TESTHEAD=1
#export cephvolumenumber=1
#export libvirt_type=xen
#export networkingplugin=linuxbridge
#export forwardmode="route"
#export NOQACROWBARDOWNLOAD=1
export net_admin=$(cloudadminnet $n)
export net_ironic=$(cloudironicnet $n)
export net_public=$(cloudpublicnet $n)
export adminnetmask=255.255.254.0
export virtualcloud=$vcloudname$n
export cloud=$virtualcloud
export NOSETUPPORTFORWARDING=1
# If no central NFS server is in place, for exporting the various repos to the admin server,
# the default is to have NFS server running and shares exported on the
# mkcloud hypervisor, which is then always reachable on the .1 in the cloudadminnet.
export nfsserver=${nfsserver:="$(cloudadminnet $n).1"}
#exec bash -x ./mkcloud "$@"

